// <auto-generated />
using System;
using EfConfigurationProvider.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfConfigurationProvider.Core.Sqlite.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200128152718_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("EfConfigurationProvider.Core.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("User");

                    b.Property<string>("Values");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });
#pragma warning restore 612, 618
        }
    }
}
